import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class PlanCreate {
  @ApiProperty()
  name: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  billing_cycle: string;
}

export class Plan {
  @ApiProperty()
  id: number;
  @ApiProperty()
  name: string;
  @ApiProperty()
  price: string;
  @ApiProperty()
  billing_cycle: string;
}
