/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Subscription } from './Subscription.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { SubscriptionService } from './Subscription.service';
import { SubscriptionController } from './Subscription.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Subscription])],
  providers: [SubscriptionService],
  exports: [SubscriptionService],
  controllers: [SubscriptionController],
})
export class SubscriptionModule {}
