/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Subscription, SubscriptionCreate } from './dtos/Subscription.dto';
import { SubscriptionController } from './Subscription.controller';
import { SubscriptionService } from './Subscription.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('SubscriptionController', () => {
  let controller: SubscriptionController;
  let spyService: SubscriptionService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: SubscriptionService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [SubscriptionController],
      providers: [SubscriptionService, ApiServiceProvider],
    }).compile();

    controller = module.get<SubscriptionController>(SubscriptionController);
    spyService = module.get<SubscriptionService>(SubscriptionService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call SubscriptionController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call SubscriptionController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Subscription();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
