/**
 * This file generated by Apso.
 */
import { SubscriptionModule } from './Subscription/Subscription.module';
import { PlanModule } from './Plan/Plan.module';
import { CustomerModule } from './Customer/Customer.module';

export default [SubscriptionModule, PlanModule, CustomerModule];
