/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Plan } from './Plan.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { PlanService } from './Plan.service';
import { PlanController } from './Plan.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Plan])],
  providers: [PlanService],
  exports: [PlanService],
  controllers: [PlanController],
})
export class PlanModule {}
