import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class SubscriptionCreate {
  @ApiProperty()
  plan_id: string;
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  status: string;
}

export class Subscription {
  @ApiProperty()
  id: number;
  @ApiProperty()
  plan_id: string;
  @ApiProperty()
  customer_id: string;
  @ApiProperty()
  start_date: string;
  @ApiProperty()
  end_date: string;
  @ApiProperty()
  status: string;
}
